all:
	g++ -O3 -std=c++11 test_linear_equations.cpp -o test_linear_equations
	./test_linear_equations 
	g++ -O3 -std=c++11 test_polynomials.cpp -o test_polynomials
	./test_polynomials 
	g++ -O3 -std=c++11 test_continuous_colormap.cpp -o test_continuous_colormap
	./test_continuous_colormap
